---
# tasks file for podman
- name: installing podman
  package:
    name: podman
    state: present


- name: Copy todoapp directory to remote host
  copy:
    src: ./files/todoapp
    dest: /opt/

- name: Build an image
  containers.podman.podman_image:
    name: "todoapp"
    path: "/opt/todoapp"

