---
# tasks file for mariadb

  - name: Install Maria DB server
    apt:
      name: mariadb-server
      state: present
      update_cache: yes

  - name: Open mariadb ports
    ufw:
      state: enabled
      rule: allow
      port: '3306'
      proto: tcp
 
  - name: Configure mariadb to listen on all interfaces
    lineinfile:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: '^bind-address'
      line: bind-address = 0.0.0.0
    notify: Restart mariadb server

  - name: mariaDB service enable and start
    service: 
      name: mariadb
      state: started
      enabled: yes

  - name: Determine required MariaDB Python libraries
    set_fact:
      deb_mariadb_python_package: "{% if 'python3' in discovered_interpreter_python|default('') %}python3-pymysql{% else %}python-pymysql{% endif %}"

  - name: Install python mariadb driver
    apt:
      name: "{{ deb_mariadb_python_package }}"
      state: present
