---
# tasks file for mariadb

  - name: Install Maria DB server
    apt:
      name: "{{ item }}"      
      state: present
      update_cache: yes
    loop:
      - mariadb-server
      - mariadb-client
      - python3-pip

  - name: Install PyMySQL with pip
    pip:
      name: PyMySQL
      executable: pip3
      extra_args: --user

  - name: Open mariadb ports
    ufw:
      state: enabled
      rule: allow
      port: '3306'
      proto: tcp
 
  - name: Configure mariadb to listen on all interfaces
    lineinfile:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: '^bind-address'
      line: bind-address = 0.0.0.0
    notify: Restart mariadb server

  - name: mariaDB service enable and start
    service: 
      name: mariadb
      state: started
      enabled: yes

    # MYSQL Secure Installation

  - name: MariaDB root password Update
    mysql_user:
      login_unix_socket: /var/run/mysqld/mysqld.sock
      login_user: root
      login_password: "{{ rootpass }}"
      check_implicit_admin: true
      name: root
      host: "{{ item }}"
      password: "{{ rootpass }}"
    loop:
      - 127.0.0.1
      - localhost
      - 192.168.56.%

  - name: Anonymous user delete
    mysql_user:
      login_host: localhost
      login_user: root
      login_password: "{{ rootpass }}"
      name: ""
      host_all: yes
      state: absent

  - name: Delete test database
    mysql_db:
      login_host: localhost
      login_user: root
      login_password: "{{ rootpass }}"
      name: test
      state: absent      
