---

  - name: Update all available packages for RedHat servers
    yum:
      name: "*"
      state: latest
    notify: Restart server
    when: ansible_os_family == "RedHat"

  - name: Update all available packages for Debian servers
    apt:
      name: "*"
      state: latest
      update_cache: yes
    notify: Restart server
    when: ansible_os_family == "Debian" 

  - name: Enable firewall and allow ssh connections on Ubuntu
    ufw:
      state: enabled
      rule: allow
      port: '22'
      proto: tcp
    when: ansible_os_family == "Debian"

