---

- hosts: linux
  become: yes  
  remote_user: sysadmin
  vars_file: 
    - roles/ansibleuser/vars/ansiblepass.yml
  tasks:

    - name: Creates ansible user
      user:
        name: ansible
        state: present
        groups: sudo
        append: yes
        password: "{{ ansiblepass }}"

    - name: installs Public key of the ansible user
      authorized_key:
        user: ansible
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"  
        state: present
