---
    - name: installs Public key in sysadmin user
      authorized_key:
        user: sysadmin
        key: "{{ lookup('file', '/home/sysadmin/.ssh/id_rsa.pub') }}"
        state: present

    - name: Creates ansible user
      user:
        name: ansible
        state: present
        password: "{{ ansiblepass }}"

    - name: Gives sudo privileges to ansible user on Redhat
      shell: usermod -aG wheel ansible
      when: ansible_os_family == 'RedHat'

    - name: Gives sudo privileges to ansible user on Debian
      shell: usermod -aG sudo ansible
      when: ansible_os_family == 'Debian'

    - name: installs Public key in ansible user
      authorized_key:
        user: ansible
        key: "{{ lookup('file', '/home/sysadmin/.ssh/id_rsa.pub') }}"  
        state: present
